# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

jobs:
  site-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branches 🔀
        uses: actions/checkout@v2

      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main

      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
